[package]
name = "sealed-bid-auction"
version = "0.1.12"
edition = "2021"
publish = false
description = "Sealed-Bid Auction"

[dependencies]
tfhe = { workspace = true, features = ["software-prng"] }
axum.workspace = true
health.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
