[package]
name = "sealed-bid-auction"
version = "0.1.16"
edition = "2021"
publish = false
description = "Sealed-Bid Auction"

[dependencies]
base64 = "0.22.1"
bincode = "1.3.3"
tfhe = { workspace = true, features = ["software-prng"] }
axum.workspace = true
health.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
