[package]
name = "encrypted-genomics"
version = "0.1.14"
edition = "2021"
publish = false
description = "Encrypted Genomics"

[dependencies]
tfhe = { workspace = true, features = ["software-prng"] }
axum.workspace = true
health.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
