[package]
name = "encrypted-program-execution"
version = "0.1.4"
edition = "2021"
publish = false
description = "Encrypted Program Execution"

[dependencies]
tfhe = { workspace = true, features = ["software-prng"] }
axum.workspace = true
health.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
