[package]
name = "encrypted-program-execution"
version = "0.1.22"
edition = "2021"
publish = false
description = "Encrypted Program Execution"

[dependencies]
tfhe = { workspace = true, features = ["software-prng"] }
rayon = "1.11.0"
axum = { workspace = true, features = ["ws"] }
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
bincode = "1.3.3"
tower-http = { version = "0.6.8", features = ["cors"] }
base64 = "0.22.1"
serde_json.workspace = true
health.workspace = true

[dev-dependencies]
tower = "0.5"
