[package]
name = "encrypted-key-value-store"
version = "0.1.20"
edition = "2021"
publish = false
description = "Encrypted Key-Value Store"

[dependencies]
axum.workspace = true
health.workspace = true
metrics-exporter.workspace = true
observability.workspace = true
openapi-docs.workspace = true
serde.workspace = true
serde_json.workspace = true
tfhe.workspace = true
aide.workspace = true
schemars.workspace = true

redis = { version = "0.25", features = ["tokio-comp"] } # TODO() update redis version
bincode = "1.3.3"
rayon = "1.12.0"
dotenvy = "0.15.7"
axum-test = "20.1.0"
uuid = { version = "1.23.1", features = ["v4"] }
tokio = "1.52.3"
reqwest = { version = "0.13.4", features = ["json"] }

[dev-dependencies]
serial_test = "3.5.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.test]
inherits = "release"
