[package]
name = "encrypted-image-processing"
version = "0.1.13"
edition = "2021"
publish = false
description = "Encrypted Image Processing"

[dependencies]
tfhe = { workspace = true, features = ["software-prng"] }
axum.workspace = true
health.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
image = "0.25.10"
rayon = "1.12.0"
