apiVersion: v2
name: argocd
description: ArgoCD GitOps Controller für den tfhe-crypto Cluster
type: application
version: 0.1.0

dependencies:
  - name: argo-cd
    version: "7.7.11"
    repository: https://argoproj.github.io/argo-helm
