{{- if .Values.postgresRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ .Chart.Name }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.postgresRoute.gateway.name }}
      namespace: {{ .Values.postgresRoute.gateway.namespace }}
      sectionName: {{ .Values.postgresRoute.gateway.sectionName }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-postgres
          port: 5432
{{- end }}
