[package]
name = "encrypted-statistics-service"
version = "0.1.7"
edition = "2021"
publish = false
description = "Encrypted Statistics Service"

[dependencies]
tfhe = { workspace = true, features = ["software-prng"] }
axum.workspace = true
health.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon = "1"
bincode = "1"
base64 = "0.22"
