[package]
name = "encrypted-leaderboard"
version = "0.1.16"
edition = "2021"
publish = false
description = "Encrypted Leaderboard"

[dependencies]
tfhe = { workspace = true, features = ["software-prng"] }
axum.workspace = true
health.workspace = true
metrics-exporter.workspace = true
observability.workspace = true
openapi-docs.workspace = true
tracing = "0.1"
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
base64 = "0.22.1"
bincode = "1.3.3"
rayon = "1.10"
aide.workspace = true
schemars.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
serde_json.workspace = true
