[package]
name = "encrypted-leaderboard"
version = "0.1.7"
edition = "2021"
publish = false
description = "Encrypted Leaderboard"

[dependencies]
tfhe = { workspace = true, features = ["software-prng"] }
axum.workspace = true
health.workspace = true
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
serde_json.workspace = true
base64 = "0.22.1"
bincode = "1.3.3"
