### Put
POST http://localhost:8080/keys
Content-Type: application/json
X-User-Id: UserID_OR_HASH

{
  "key": "str",
  "value": "str",
  "ttl": 240
}
> {%
    client.test("Test status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get
GET http://localhost:8080/keys/str
Content-Type: application/json
X-User-Id: UserID_OR_HASH

> {%
    client.test("Test status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get all
GET http://localhost:8080/keys
Content-Type: application/json
X-User-Id: UserID_OR_HASH

> {%
    client.test("Test status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Exists
GET http://localhost:8080/keys/exists/str
Content-Type: application/json
X-User-Id: UserID_OR_HASH

> {%
    client.test("Test status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete
DELETE http://localhost:8080/keys/str
Content-Type: application/json
X-User-Id: UserID_OR_HASH

> {%
    client.test("Test status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete all
DELETE http://localhost:8080/keys
Content-Type: application/json
X-User-Id: UserID_OR_HASH

> {%
    client.test("Test status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
