name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - encrypted-key-value-store
          - encrypted-age-verification
          - encrypted-voting-polling
          - sealed-bid-auction
          - encrypted-statistics-service
          - encrypted-genomics
          - encrypted-image-processing
          - encrypted-leaderboard
          - encrypted-program-execution
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Format
        run: cargo fmt -p ${{ matrix.service }} -- --check

      - name: Clippy
        run: cargo clippy -p ${{ matrix.service }} -- -D warnings

      - name: Test
        run: cargo test -p ${{ matrix.service }}
